DROP TABLE IF EXISTS FISH;
CREATE TABLE FISH(
    timer INTEGER
);

DROP TABLE IF EXISTS NUMBERS;
CREATE TABLE NUMBERS(
    timer INTEGER,
    many INTEGER
);

.separator " " ","
.import input/da06.txt FISH
.separator ", " "\n"

INSERT INTO NUMBERS (timer, many) VALUES
(0, 0),
(1, 0),
(2, 0),
(3, 0),
(4, 0),
(5, 0),
(6, 0),
(7, 0),
(8, 0);

UPDATE NUMBERS SET many = (SELECT COUNT(*) FROM FISH WHERE FISH.timer = NUMBERS.timer);

-- Manually unwrap 256 iterations of a FOR loop.
-- Sounds better than "I don't know how loops work in SQLite".
UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

select SUM(many) FROM NUMBERS;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

UPDATE NUMBERS SET timer = timer-1;
INSERT INTO NUMBERS (timer, many) VALUES (8, (SELECT many FROM NUMBERS WHERE timer=-1));
UPDATE NUMBERS SET many = many + (SELECT many FROM NUMBERS WHERE timer=-1) WHERE timer=6;
DELETE FROM NUMBERS WHERE timer=-1;

select SUM(many) FROM NUMBERS;
